export const employees = [
  {
    employee: "Ye Min Htun",
    location: "Yangon Office",
    email: "yeminhtun@gmail.com",
    phone: "+857 9999 9999",
    department: "Marketing",
    employeeCode: "004-343",
    customTags: "Intern",
    position: "UX Designer",
    NRC: "12/DGM(N)/007006",
    manager: "Myo Zaw Hein",
    managerPosition: "CEO",
    joinnedDate: "12.2.2021",
    terminateDate: "-",
  },
  {
    employee: "Hnin Wai Phyo",
    location: "Mandalay Office",
    email: "hninwai@gmail.com",
    phone: "+857 8888 8888",
    department: "Finance",
    employeeCode: "004-344",
    customTags: "Full-time",
    position: "Accountant",
    NRC: "12/DGM(N)/008007",
    manager: "Maung Maung",
    managerPosition: "CFO",
    joinnedDate: "5.3.2020",
    terminateDate: "-",
  },
  {
    employee: "Zaw Zaw Aung",
    location: "Nay Pyi Taw Office",
    email: "zawzawaung@gmail.com",
    phone: "+857 7777 7777",
    department: "HR",
    employeeCode: "004-345",
    customTags: "Contract",
    position: "HR Manager",
    NRC: "12/DGM(N)/009008",
    manager: "Kyaw Kyaw",
    managerPosition: "Director",
    joinnedDate: "1.6.2019",
    terminateDate: "-",
  },
  {
    employee: "Myat Min Oo",
    location: "Yangon Office",
    email: "myatminoo@gmail.com",
    phone: "+857 6666 6666",
    department: "IT",
    employeeCode: "004-346",
    customTags: "Full-time",
    position: "Software Engineer",
    NRC: "12/DGM(N)/010009",
    manager: "Aung Aung",
    managerPosition: "CTO",
    joinnedDate: "10.1.2022",
    terminateDate: "-",
  },
  {
    employee: "Thiri Shwe Yee",
    location: "Yangon Office",
    email: "thirishweyee@gmail.com",
    phone: "+857 3333 3333",
    department: "Marketing",
    employeeCode: "004-349",
    customTags: "Intern",
    position: "Content Writer",
    NRC: "12/DGM(N)/013012",
    manager: "Myo Zaw Hein",
    managerPosition: "CEO",
    joinnedDate: "25.3.2022",
    terminateDate: "-",
  },
  {
    employee: "Aye Chan Mon",
    location: "Mandalay Office",
    email: "ayechanmon@gmail.com",
    phone: "+857 2222 2222",
    department: "Finance",
    employeeCode: "004-350",
    customTags: "Contract",
    position: "Financial Analyst",
    NRC: "12/DGM(N)/014013",
    manager: "Maung Maung",
    managerPosition: "CFO",
    joinnedDate: "20.10.2021",
    terminateDate: "-",
  },
  {
    employee: "Nyein Chan Aung",
    location: "Nay Pyi Taw Office",
    email: "nyeinchanaung@gmail.com",
    phone: "+857 1111 1111",
    department: "HR",
    employeeCode: "004-351",
    customTags: "Full-time",
    position: "Recruitment Specialist",
    NRC: "12/DGM(N)/015014",
    manager: "Kyaw Kyaw",
    managerPosition: "Director",
    joinnedDate: "3.11.2020",
    terminateDate: "-",
  },
  {
    employee: "Win Thant Zin",
    location: "Bago Office",
    email: "winthantzin@gmail.com",
    phone: "+857 0000 0000",
    department: "Operations",
    employeeCode: "004-352",
    customTags: "Full-time",
    position: "Logistics Coordinator",
    NRC: "12/DGM(N)/016015",
    manager: "Hla Hla",
    managerPosition: "COO",
    joinnedDate: "17.7.2021",
    terminateDate: "-",
  },
  {
    employee: "Su Su Lin",
    location: "Bago Office",
    email: "susulin@gmail.com",
    phone: "+857 5555 5555",
    department: "Operations",
    employeeCode: "004-347",
    customTags: "Part-time",
    position: "Operations Manager",
    NRC: "12/DGM(N)/011010",
    manager: "Hla Hla",
    managerPosition: "COO",
    joinnedDate: "15.8.2020",
    terminateDate: "-",
  },
  {
    employee: "Kyaw Min Thant",
    location: "Yangon Office",
    email: "kyawminthant@gmail.com",
    phone: "+857 4444 4444",
    department: "IT",
    employeeCode: "004-348",
    customTags: "Full-time",
    position: "System Administrator",
    NRC: "12/DGM(N)/012011",
    manager: "Aung Aung",
    managerPosition: "CTO",
    joinnedDate: "1.12.2019",
    terminateDate: "-",
  },
  {
    employee: "Min Min Khaing",
    location: "Yangon Office",
    email: "minminkhaing@gmail.com",
    phone: "+857 1112 3333",
    department: "IT",
    employeeCode: "004-353",
    customTags: "Part-time",
    position: "Front-End Developer",
    NRC: "12/DGM(N)/017016",
    manager: "Aung Aung",
    managerPosition: "CTO",
    joinnedDate: "15.5.2021",
    terminateDate: "-",
  },
  {
    employee: "San Thida Moe",
    location: "Mandalay Office",
    email: "santhidamoe@gmail.com",
    phone: "+857 2223 4444",
    department: "Finance",
    employeeCode: "004-354",
    customTags: "Full-time",
    position: "Budget Analyst",
    NRC: "12/DGM(N)/018017",
    manager: "Maung Maung",
    managerPosition: "CFO",
    joinnedDate: "10.2.2021",
    terminateDate: "-",
  },
  {
    employee: "Kyaw Zin Latt",
    location: "Nay Pyi Taw Office",
    email: "kyawzinlatt@gmail.com",
    phone: "+857 3334 5555",
    department: "HR",
    employeeCode: "004-355",
    customTags: "Full-time",
    position: "Training Specialist",
    NRC: "12/DGM(N)/019018",
    manager: "Kyaw Kyaw",
    managerPosition: "Director",
    joinnedDate: "7.7.2020",
    terminateDate: "-",
  },
  {
    employee: "Thura Tun",
    location: "Yangon Office",
    email: "thuratun@gmail.com",
    phone: "+857 4445 6666",
    department: "Marketing",
    employeeCode: "004-356",
    customTags: "Intern",
    position: "Social Media Specialist",
    NRC: "12/DGM(N)/020019",
    manager: "Myo Zaw Hein",
    managerPosition: "CEO",
    joinnedDate: "2.4.2022",
    terminateDate: "-",
  },
  {
    employee: "Zin Zin Htet",
    location: "Bago Office",
    email: "zinzinhtet@gmail.com",
    phone: "+857 5556 7777",
    department: "Operations",
    employeeCode: "004-357",
    customTags: "Full-time",
    position: "Procurement Officer",
    NRC: "12/DGM(N)/021020",
    manager: "Hla Hla",
    managerPosition: "COO",
    joinnedDate: "9.9.2020",
    terminateDate: "-",
  },
];

export const departments = [
  { department: "IT", id: "1" },
  { department: "Marketing", id: "2" },
  { department: "Finance", id: "3" },
  { department: "HR", id: "4" },
  { department: "Operations", id: "5" },
  { department: "Legal", id: "6" },
  { department: "Sales", id: "7" },
  { department: "Customer Support", id: "8" },
  { department: "R&D", id: "9" },
  { department: "Procurement", id: "10" },
];
